# Generated by Django 5.1 on 2024-08-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
    ]
