# Generated by Django 5.1 on 2024-08-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_history_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
