version: "3.3"

services:

    razdorov_lk:
      restart: always
      build:
        context: /lk
      ports:
        - "8000:8000"
      command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
      volumes:
        - ./lk/razdorovLk:/lk
#
