# Generated by Django 5.1 on 2024-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название задачи')),
                ('description', models.CharField(max_length=150, verbose_name='Краткое описание задачи')),
                ('coins', models.IntegerField(verbose_name='Количество баллов')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачу',
            },
        ),
    ]
