# Generated by Django 5.1 on 2024-08-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
    ]
