# Generated by Django 5.1 on 2024-08-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('shop', '0005_delete_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='operationName',
        ),
        migrations.AddField(
            model_name='history',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopitem', verbose_name='Услуга'),
        ),
    ]
