# Generated by Django 5.1 on 2024-08-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст заявки')),
                ('topic', models.CharField(choices=[('complaint', 'Жалоба'), ('wish', 'Пожелание')], max_length=15, verbose_name='Тема')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
