# Generated by Django 5.1 on 2024-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Жалобу', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AddField(
            model_name='support',
            name='comment',
            field=models.CharField(max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
