# Generated by Django 5.1 on 2024-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_support_options_support_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='comment',
            field=models.TextField(max_length=300, null=True, verbose_name='Комментарий'),
        ),
    ]
