# Generated by Django 5.1 on 2024-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_support_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
