# Generated by Django 5.1 on 2024-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_support_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='dateClose',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
