# Generated by Django 5.1 on 2024-08-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название стадии')),
                ('description', models.TextField(max_length=300, verbose_name='Описании стадии')),
                ('video', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID видео из Youtube')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Стадию',
                'verbose_name_plural': 'Стадии',
            },
        ),
        migrations.CreateModel(
            name='UsersAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('secondName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('personalId', models.CharField(max_length=30, verbose_name='Личный ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудника',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Affairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfConclusion', models.DateField(null=True, verbose_name='Дата заключения сделки')),
                ('depositPaymentDate', models.DateField(null=True, verbose_name='Дата оплаты депозита')),
                ('dateOfSendingToCourt', models.DateField(null=True, verbose_name='Дата отправки в суд')),
                ('caseNumber', models.CharField(max_length=100, null=True, verbose_name='Номер дела')),
                ('dateOfBankruptcy', models.DateField(null=True, verbose_name='Дата признания банкротом')),
                ('completionDate', models.DateField(null=True, verbose_name='Дата завершения')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currentStateOfAffairs.stageaffairs', verbose_name='Текущая стадия')),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss', to='currentStateOfAffairs.usersaffairs', verbose_name='Руководитель')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='currentStateOfAffairs.usersaffairs', verbose_name='Менеджер по продажам')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support', to='currentStateOfAffairs.usersaffairs', verbose_name='Менеджер поддержки')),
            ],
        ),
    ]
