# Generated by Django 5.1 on 2024-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentStateOfAffairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageaffairs',
            name='stageId',
            field=models.CharField(default='', max_length=15, verbose_name='ID стадии'),
            preserve_default=False,
        ),
    ]
