# Generated by Django 5.1 on 2024-08-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentStateOfAffairs', '0002_stageaffairs_stageid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affairs',
            options={'verbose_name': 'Дела', 'verbose_name_plural': 'Дела'},
        ),
    ]
