# Generated by Django 5.1 on 2024-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentStateOfAffairs', '0003_alter_affairs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='idDeal',
            field=models.IntegerField(null=True, unique=True, verbose_name='ID сделки'),
        ),
        migrations.AlterField(
            model_name='usersaffairs',
            name='personalId',
            field=models.CharField(max_length=30, unique=True, verbose_name='Личный ID'),
        ),
    ]
