# Generated by Django 5.1 on 2024-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentStateOfAffairs', '0004_affairs_iddeal_alter_usersaffairs_personalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairs',
            name='idDeal',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID сделки'),
        ),
    ]
