# Generated by Django 5.1 on 2024-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentStateOfAffairs', '0005_alter_affairs_iddeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='linkToKadArbitr',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на КадАрбитр'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='caseNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер дела'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='completionDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='dateOfBankruptcy',
            field=models.DateField(blank=True, null=True, verbose_name='Дата признания банкротом'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='dateOfConclusion',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения сделки'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='dateOfSendingToCourt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки в суд'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='depositPaymentDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты депозита'),
        ),
    ]
