# Generated by Django 5.1 on 2024-08-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentStateOfAffairs', '0006_affairs_linktokadarbitr_alter_affairs_casenumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersAffairs',
            new_name='Employees',
        ),
    ]
