# Generated by Django 5.1 on 2024-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
