# Generated by Django 5.1 on 2024-08-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='idConactFromBitrix',
        ),
    ]
