# Generated by Django 5.1 on 2024-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_idconactfrombitrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Количество бонусов'),
        ),
    ]
