# Generated by Django 5.1 on 2024-08-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бонусов'),
        ),
    ]
