# Generated by Django 5.1 on 2024-08-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_coins'),
        ('currentStateOfAffairs', '0003_alter_affairs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='affair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currentStateOfAffairs.affairs', verbose_name='Состояние дела'),
        ),
    ]
