# Generated by Django 5.1 on 2024-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_affair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='idDealFromBitrix',
        ),
    ]
