# Generated by Django 5.1 on 2024-08-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_iddealfrombitrix'),
        ('currentStateOfAffairs', '0006_affairs_linktokadarbitr_alter_affairs_casenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='affair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currentStateOfAffairs.affairs', verbose_name='Состояние дела'),
        ),
    ]
