# Generated by Django 5.1 on 2024-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_affair'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='idLeadFromBitrix24',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID лида из Битрикс24'),
        ),
    ]
